const JWT_ACCESS_TOKEN_EXP = 5 * 60;
const JWT_REFRESH_TOKEN_EXP = 7 * 86400;
const JWT_NAME = "jwt";
const JWT_SECRET = Bun.env.JWT_SECRET ?? "SECRET_KEY";

export { JWT_ACCESS_TOKEN_EXP, JWT_NAME, JWT_REFRESH_TOKEN_EXP, JWT_SECRET };
